name: CI pipeline
on: [push, pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out the code
        uses: actions/checkout@v2.3.1

      - name: Go dependencies
        run: go mod download

      - name: Go test
        run: go test -short ./...
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2.3.1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.0.0
        with:
          version: v1.30
          args: --enable goimports
