name: CI pipeline
on:
  push:
    branches-ignore:
     - 'dependabot/**'
  pull_request:

permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out the code
        uses: actions/checkout@v2.4.0

      - name: Go dependencies
        run: go mod download

      - name: Go test
        run: go test ./...

  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v2.4.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.39.0

  coverage:
    name: Gather test coverage
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out the code
        uses: actions/checkout@v2.4.0

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0

      - name: Setup coverage tools
        run: go get github.com/t-yuki/gocover-cobertura

      - name: Generate coverage
        run: go test -coverprofile=coverage.txt -covermode count ./... && gocover-cobertura < coverage.txt > coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

